#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# HospiPlan Phase 3 : GUIDE DE DÉMARRAGE RAPIDE
# ═══════════════════════════════════════════════════════════════

echo "🚀 HospiPlan Phase 3 - Démarrage rapide"
echo "========================================"

# Configuration
DJANGO_PROJECT="c:\\Users\\pcoko\\Les Etudes\\Année 4\\IABD\\Bootcamp\\Bootcamp phase 2\\environnement_project\\environnement"
FRONTEND_PROJECT="c:\\Users\\pcoko\\Les Etudes\\Année 4\\IABD\\Bootcamp\\Bootcamp phase 2\\environnement_project\\hospiplan-frontend"
VENV_PATH="c:\\Users\\pcoko\\Les Etudes\\Année 4\\IABD\\Bootcamp\\Bootcamp phase 2\\environnement_project\\myenv\\Scripts\\activate"

echo ""
echo "📋 Étape 1 : Activer l'environnement virtuel"
echo "─────────────────────────────────────────"
# Sur Windows PowerShell :
# & "c:\Users\pcoko\Les Etudes\Année 4\IABD\Bootcamp\Bootcamp phase 2\environnement_project\myenv\Scripts\Activate.ps1"

# Ou sur Windows CMD :
# call "c:\Users\pcoko\Les Etudes\Année 4\IABD\Bootcamp\Bootcamp phase 2\environnement_project\myenv\Scripts\activate.bat"

echo "✅ Activez le virtual environment"
echo ""

echo "📋 Étape 2 : Créer les migrations"
echo "─────────────────────────────────"
echo "cd $DJANGO_PROJECT"
echo "python manage.py makemigrations hospiplan"
echo ""

echo "📋 Étape 3 : Appliquer les migrations"
echo "─────────────────────────────────────"
echo "python manage.py migrate hospiplan"
echo ""

echo "📋 Étape 4 : Charger les configurations par défaut"
echo "──────────────────────────────────────────────────"
echo "python manage.py shell << EOF"
echo "from hospiplan.models import ConstrainteSouple"
echo ""
echo "ConstrainteSouple.objects.all().delete()"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='night_consecutive',"
echo "    weight=1.0,"
echo "    is_active=True,"
echo "    description='Éviter plus de 3 nuits consécutives'"
echo ")"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='preferences',"
echo "    weight=0.5,"
echo "    is_active=False,"
echo "    description='Respecter les préférences de créneaux'"
echo ")"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='workload_equity',"
echo "    weight=1.5,"
echo "    is_active=True,"
echo "    description='Équilibrer la charge (écart-type)'"
echo ")"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='service_changes',"
echo "    weight=0.8,"
echo "    is_active=True,"
echo "    description='Minimiser changements de service'"
echo ")"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='weekend_equity',"
echo "    weight=1.0,"
echo "    is_active=True,"
echo "    description='Équité dans les week-ends'"
echo ")"
echo ""
echo "ConstrainteSouple.objects.create("
echo "    constraint_type='continuity',"
echo "    weight=0.3,"
echo "    is_active=False,"
echo "    description='Favoriser continuité de soins'"
echo ")"
echo ""
echo "exit()"
echo "EOF"
echo ""

echo "📋 Étape 5 : Tester depuis le shell Django"
echo "─────────────────────────────────────────────"
echo "python manage.py shell << EOF"
echo "from hospiplan.planning_generator import generer_planning_simple"
echo "from datetime import date"
echo ""
echo "planning = generer_planning_simple("
echo "    date(2025, 1, 6),"
echo "    date(2025, 1, 12),"
echo "    name='Planning Test Semaine 1'"
echo ")"
echo ""
echo "print(f'✅ Planning généré: {planning.name}')"
echo "print(f'   Score: {planning.score_total:.2f}')"
echo "print(f'   Affectations: {planning.affectations.count()}')"
echo ""
echo "score = planning.score_detail"
echo "print(f'\\nDétail du score:')"
echo "print(f'  - Nuits consécutives: {score.penalty_night_consecutive:.2f}')"
echo "print(f'  - Équité charge: {score.penalty_workload_equity:.2f}')"
echo "print(f'  - Changements service: {score.penalty_service_changes:.2f}')"
echo "print(f'  - Équité week-ends: {score.penalty_weekend_equity:.2f}')"
echo "exit()"
echo "EOF"
echo ""

echo "📋 Étape 6 : Lancer le serveur Django"
echo "──────────────────────────────────────"
echo "python manage.py runserver"
echo ""
echo "✅ API disponible sur : http://localhost:8000/api/hospiplan/"
echo ""

echo "📋 Étape 7 : Lancer le frontend React (dans une autre console)"
echo "────────────────────────────────────────────────────────────"
echo "cd $FRONTEND_PROJECT"
echo "npm install"
echo "npm start"
echo ""
echo "✅ Frontend disponible sur : http://localhost:3000/"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎯 Vos endpoints disponibles :"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📍 POST /api/hospiplan/plannings/generate/"
echo "   └─ Générer un nouveau planning"
echo "   Exemple:"
echo "   {"
echo "     \"start_date\": \"2025-01-06\","
echo "     \"end_date\": \"2025-01-12\","
echo "     \"name\": \"Planning Semaine 1\","
echo "     \"algorithm\": \"least-loaded\""
echo "   }"
echo ""
echo "📍 GET /api/hospiplan/plannings/"
echo "   └─ Lister tous les plannings"
echo ""
echo "📍 GET /api/hospiplan/plannings/{id}/"
echo "   └─ Voir le détail d'un planning"
echo ""
echo "📍 GET /api/hospiplan/plannings/{id}/score/"
echo "   └─ Voir le score des contraintes molles"
echo ""
echo "📍 GET /api/hospiplan/plannings/{id}/affectations/"
echo "   └─ Lister les affectations d'un planning"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✨ Interface Web :"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🌐 http://localhost:3000/plannings"
echo ""
echo "Fonctionnalités :"
echo "  ✓ Générer un planning (dates + algorithme)"
echo "  ✓ Voir la liste des plannings"
echo "  ✓ Voir le score global"
echo "  ✓ Voir le détail des pénalités"
echo "  ✓ Voir la liste des affectations"
echo "  ✓ Ajouter/modifier des affectations"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🔗 Documentation :"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION_PHASE_3.md"
echo "   └─ Guide complet avec tous les détails"
echo ""
echo "📚 PSEUDO_CODE_PHASE_3.md"
echo "   └─ Pseudo-code détaillé de l'heuristique"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 C'est prêt ! Commencez à générer des plannings ! 🎉"
echo "═══════════════════════════════════════════════════════════════"
