# Generated by Django 6.0.3 on 2026-04-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('impacts_quota', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('leave_days_per_year', models.IntegerField(blank=True, null=True)),
                ('night_shift_allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bed_capacity', models.IntegerField()),
                ('criticality_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_hours', models.IntegerField()),
                ('requires_rest_after', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.service')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_staff', models.IntegerField(default=1)),
                ('max_staff', models.IntegerField(blank=True, null=True)),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.careunit')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.shifttype')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospiplan.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospiplan.staff'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('workload_percent', models.IntegerField(default=100)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.contracttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.absencetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.certification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_certifications', to='hospiplan.certification')),
                ('required_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_certifications', to='hospiplan.certification')),
            ],
            options={
                'unique_together': {('parent_cert', 'required_cert')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequiredCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.certification')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.shift')),
            ],
            options={
                'unique_together': {('shift', 'certification')},
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
            options={
                'unique_together': {('staff', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StaffSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.specialty')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.staff')),
            ],
            options={
                'unique_together': {('staff', 'specialty')},
            },
        ),
    ]
