# Generated by Django 6.0.3 on 2026-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soignant',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
