# Generated by Django 6.0.3 on 2026-04-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiplan', '0002_soignant_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='staff',
        ),
        migrations.AddField(
            model_name='absence',
            name='soignant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospiplan.soignant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='seuil_minimum',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_garde', models.CharField(choices=[('jour', 'Jour'), ('nuit', 'Nuit'), ('weekend', 'Weekend')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('min_soignants', models.IntegerField(default=1)),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.careunit')),
            ],
        ),
        migrations.CreateModel(
            name='SoignantCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.certification')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hospiplan.soignant')),
            ],
        ),
        migrations.CreateModel(
            name='SoignantContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.contracttype')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='hospiplan.soignant')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.soignant')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.poste')),
            ],
            options={
                'unique_together': {('soignant', 'poste')},
            },
        ),
        migrations.CreateModel(
            name='PosteCertificationRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.certification')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_requises', to='hospiplan.poste')),
            ],
            options={
                'unique_together': {('poste', 'certification')},
            },
        ),
    ]
