# Generated by Django 6.0.4 on 2026-04-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiplan', '0003_remove_absence_staff_absence_soignant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='care_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospiplan.careunit'),
        ),
    ]
