# Generated by Django 6.0.4 on 2026-04-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiplan', '0004_alter_poste_care_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstrainteSouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('night_consecutive', 'Nuits consécutives'), ('preferences', 'Préférences de créneaux'), ('workload_equity', 'Équité de charge'), ('service_changes', 'Changements de service'), ('weekend_equity', 'Équité week-ends'), ('continuity', 'Continuité de soins')], max_length=50, unique=True)),
                ('weight', models.FloatField(default=1.0, help_text='Poids (0 = ignoré, >0 = actif)')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contraintes souples',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Généré'), ('edited', 'Modifié'), ('approved', 'Approuvé'), ('published', 'Publié')], default='draft', max_length=20)),
                ('score_total', models.FloatField(default=0.0, help_text='Score des contraintes molles (plus bas = mieux)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by_algorithm', models.CharField(default='least-loaded', help_text='Heuristique utilisée pour générer ce planning', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='soignant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soignant actif dans le système'),
        ),
        migrations.CreateModel(
            name='ScorePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_night_consecutive', models.FloatField(default=0.0, help_text='Pénalité : trop de nuits consécutives')),
                ('penalty_preferences', models.FloatField(default=0.0, help_text='Pénalité : préférences de créneaux non respectées')),
                ('penalty_workload_equity', models.FloatField(default=0.0, help_text='Pénalité : charge inégale entre soignants (écart-type élevé)')),
                ('penalty_service_changes', models.FloatField(default=0.0, help_text='Pénalité : trop de changements de service')),
                ('penalty_weekend_equity', models.FloatField(default=0.0, help_text='Pénalité : inégalité dans les week-ends travaillés')),
                ('penalty_continuity', models.FloatField(default=0.0, help_text='Pénalité : manque de continuité de soins')),
                ('total_shifts_assigned', models.IntegerField(default=0)),
                ('uncovered_shifts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_detail', to='hospiplan.planning')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False, help_text='True si affectation modifiée manuellement après génération')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.poste')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospiplan.soignant')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='hospiplan.planning')),
            ],
            options={
                'indexes': [models.Index(fields=['planning', 'soignant'], name='hospiplan_a_plannin_78fa4f_idx'), models.Index(fields=['planning', 'poste'], name='hospiplan_a_plannin_d7f879_idx')],
                'unique_together': {('planning', 'soignant', 'poste')},
            },
        ),
    ]
